import { About } from '../layout/section-about';
import { Skills } from '../layout/section-skills';
import { FaPython, FaJava, FaNodeJs, FaReact} from 'react-icons/fa';


export const sections = [
    {
        title: 'About Me',
        content: <About />
    },
    {
        title: 'Skills',
        content: <Skills />
    }
];

export const socials = {
    linkedin: 'https://linkedin.com/in/david-gasinski/',
    youtube: 'word.com',
    github: 'https://github.com/david-gasinski'
};

export const skills = [
    {
        logo: <FaPython />,
        tech: 'Flask | Flask-Restful | Pandas | Async IO | PyTest'
    },
    {
        logo: <FaJava />,
        tech: 'SpringBoot | LWJGl 3 | JUnit'
    },
    {
        logo: <FaNodeJs />,
        tech: 'Express | Ether.js | Axios'
    },
    {
        logo: <FaReact />,
        tech: 'Next.Js | React-Router | React-Redux'
    },
    {
        logo: <FaReact />,
        tech: 'Sinatra | Sequel'
    }
];


export const projects = [
    {
        name: "Discord Bot for crypto portfolio analysis",
        description: "A discord bot which allows the user to link their wallet ID to their discord account. The user can then use a command to generate a unique link (which expires after 12 hours) to view a summary of their portolfio, including overall value, individual token balance, recent transaction, when the user bought/sold and for what price. The discord bot is made using python and discord.py, with an SQL server as the database. The unique links are generated by a react app with a springboot backend.",
        repo: "https://github.com/david-gasinski/python-crypto-bot",
        tech_stack: [
            <FaReact />,
            <FaPython />,
            <FaJava />
        ],
    },
    {
        name: "2D Java Platformer",
        description: "A simple Java game made with Java.AWT. Uses free assets found from websites such as itch.io.",
        repo: "https://github.com/david-gasinski/",
        tech_stack: [
            <FaJava />
        ],
    },
    {
        name: "Footballer Management Software",
        description: "A simple Java game made with Java.AWT. Uses free assets found from websites such as itch.io.",
        repo: "https://github.com/david-gasinski/",
        tech_stack: [
            <FaJava />
        ],
    },
]